language: php

# faster builds on docker-container setup
sudo: false

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: SYMFONY_VERSION=2.8.* COMPOSER_FLAGS='--prefer-lowest'
        - env: SYMFONY_VERSION=3.0.*
        - env: SYMFONY_VERSION=3.1.*

php:
    - 7.0
    - 7.1

before_install:
    # disable xdebug since we don't use code-coverage for now
    - if [[ $TRAVIS_PHP_VERSION != '7.0' ]]; then phpenv config-rm xdebug.ini; fi
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/validator:${SYMFONY_VERSION}" --no-update; fi;

install:
    - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: make tests
